# Generated by Django 5.1.1 on 2024-09-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShulSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('alos', models.TimeField(blank=True, null=True)),
                ('hanetz', models.TimeField(blank=True, null=True)),
                ('chatzos', models.TimeField(blank=True, null=True)),
                ('mincha_gedola', models.TimeField(blank=True, null=True)),
                ('mincha_ketana', models.TimeField(blank=True, null=True)),
                ('plag_hamincha', models.TimeField(blank=True, null=True)),
                ('shkia', models.TimeField(blank=True, null=True)),
                ('tzais', models.TimeField(blank=True, null=True)),
                ('tzais_72', models.TimeField(blank=True, null=True)),
                ('sof_zman_krias_shema_gra', models.TimeField(blank=True, null=True)),
                ('sof_zman_krias_shema_mga', models.TimeField(blank=True, null=True)),
                ('sof_zman_tfila_gra', models.TimeField(blank=True, null=True)),
                ('sof_zman_tfila_mga', models.TimeField(blank=True, null=True)),
                ('candle_lighting', models.TimeField(blank=True, null=True)),
                ('parsha', models.CharField(blank=True, max_length=100, null=True)),
                ('dafyomibavli', models.CharField(blank=True, max_length=100, null=True)),
                ('mishnayomis', models.CharField(blank=True, max_length=100, null=True)),
                ('pirkeiavos', models.CharField(blank=True, max_length=100, null=True)),
                ('tanakh_yomi', models.CharField(blank=True, max_length=100, null=True)),
                ('tehillimmonthly', models.CharField(blank=True, max_length=100, null=True)),
                ('AmudYomiBavliDirshu', models.CharField(blank=True, max_length=100, null=True)),
                ('DafYomiYerushalmi', models.CharField(blank=True, max_length=100, null=True)),
                ('yerushalmi_yomi', models.CharField(blank=True, max_length=100, null=True)),
                ('DafHashavuaBavli', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(choices=[('s', 'Sephardic'), ('a', 'Ashkenazic'), ('he', 'Hebrew'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('ru', 'Russian'), ('pl', 'Polish'), ('fi', 'Finnish'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('ashkenazi_romanian', 'Romanian (Ashk.)'), ('uk', 'Ukrainian'), ('sh', 'Sephardic + Hebrew'), ('ah', 'Ashkenazic + Hebrew')], default='s', max_length=20)),
                ('time_format', models.CharField(choices=[('12h', '12-hour'), ('24h', '24-hour')], default='12h', max_length=10)),
                ('show_seconds', models.BooleanField(default=False)),
            ],
        ),
    ]
