# Generated by Django 5.1.1 on 2024-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('time_type', models.CharField(choices=[('fixed', 'Fixed Time'), ('dynamic', 'Dynamic Time')], max_length=10)),
                ('base_time', models.CharField(blank=True, max_length=100, null=True)),
                ('offset_minutes', models.IntegerField(default=0)),
                ('fixed_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
            ],
        ),
        migrations.RemoveField(
            model_name='shulsettings',
            name='AmudYomiBavliDirshu',
        ),
        migrations.RemoveField(
            model_name='shulsettings',
            name='DafHashavuaBavli',
        ),
        migrations.RemoveField(
            model_name='shulsettings',
            name='DafYomiYerushalmi',
        ),
        migrations.RemoveField(
            model_name='shulsettings',
            name='pirkeiavos',
        ),
        migrations.RemoveField(
            model_name='shulsettings',
            name='tanakh_yomi',
        ),
        migrations.RemoveField(
            model_name='shulsettings',
            name='yerushalmi_yomi',
        ),
        migrations.AddField(
            model_name='shulsettings',
            name='daf_yomi_yerushalmi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shulsettings',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shulsettings',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shulsettings',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shulsettings',
            name='timezone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shulsettings',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
