# Generated by Django 5.1.1 on 2024-09-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0002_customtime_remove_shulsettings_amudyomibavlidirshu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtime',
            name='calculated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
