# Generated by Django 5.1.1 on 2024-09-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0003_customtime_calculated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtime',
            name='daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customtime',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], null=True),
        ),
    ]
