# Generated by Django 5.0.8 on 2025-07-24 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0004_customtime_daily_alter_customtime_day_of_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('timezone', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('s', 'Sephardic'), ('a', 'Ashkenazic'), ('he', 'Hebrew'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('ru', 'Russian'), ('pl', 'Polish'), ('fi', 'Finnish'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('ashkenazi_romanian', 'Romanian (Ashk.)'), ('uk', 'Ukrainian'), ('sh', 'Sephardic + Hebrew'), ('ah', 'Ashkenazic + Hebrew')], default='s', max_length=20)),
                ('time_format', models.CharField(choices=[('12h', '12-hour'), ('24h', '24-hour')], default='12h', max_length=10)),
                ('show_seconds', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alos', models.TimeField(blank=True, null=True)),
                ('hanetz', models.TimeField(blank=True, null=True)),
                ('chatzos', models.TimeField(blank=True, null=True)),
                ('mincha_gedola', models.TimeField(blank=True, null=True)),
                ('mincha_ketana', models.TimeField(blank=True, null=True)),
                ('plag_hamincha', models.TimeField(blank=True, null=True)),
                ('shkia', models.TimeField(blank=True, null=True)),
                ('tzais', models.TimeField(blank=True, null=True)),
                ('tzais_72', models.TimeField(blank=True, null=True)),
                ('sof_zman_krias_shema_gra', models.TimeField(blank=True, null=True)),
                ('sof_zman_krias_shema_mga', models.TimeField(blank=True, null=True)),
                ('sof_zman_tfila_gra', models.TimeField(blank=True, null=True)),
                ('sof_zman_tfila_mga', models.TimeField(blank=True, null=True)),
                ('candle_lighting', models.TimeField(blank=True, null=True)),
                ('parsha', models.CharField(blank=True, max_length=100)),
                ('dafyomibavli', models.CharField(blank=True, max_length=100)),
                ('mishnayomis', models.CharField(blank=True, max_length=100)),
                ('tehillimmonthly', models.CharField(blank=True, max_length=100)),
                ('daf_yomi_yerushalmi', models.CharField(blank=True, max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shuls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ShulSettings',
        ),
        migrations.AlterField(
            model_name='customtime',
            name='internal_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='customtime',
            name='shul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_times', to='zmanim_app.shul'),
        ),
        migrations.AlterUniqueTogether(
            name='customtime',
            unique_together={('shul', 'internal_name')},
        ),
    ]
