# Generated by Django 5.0.8 on 2025-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0005_shul_delete_shulsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
