# Generated by Django 5.0.8 on 2025-10-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0006_shul_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shul',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
