# Generated by Django 5.0.8 on 2025-10-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0007_alter_shul_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shul',
            name='alos',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='candle_lighting',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='chatzos',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='daf_yomi_yerushalmi',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='dafyomibavli',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='hanetz',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='mincha_gedola',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='mincha_ketana',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='mishnayomis',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='parsha',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='plag_hamincha',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='shkia',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='sof_zman_krias_shema_gra',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='sof_zman_krias_shema_mga',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='sof_zman_tfila_gra',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='sof_zman_tfila_mga',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='tehillimmonthly',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='tzais',
        ),
        migrations.RemoveField(
            model_name='shul',
            name='tzais_72',
        ),
        migrations.CreateModel(
            name='DailyZmanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('alos', models.TimeField(blank=True, null=True)),
                ('hanetz', models.TimeField(blank=True, null=True)),
                ('chatzos', models.TimeField(blank=True, null=True)),
                ('mincha_gedola', models.TimeField(blank=True, null=True)),
                ('mincha_ketana', models.TimeField(blank=True, null=True)),
                ('plag_hamincha', models.TimeField(blank=True, null=True)),
                ('shkia', models.TimeField(blank=True, null=True)),
                ('tzais', models.TimeField(blank=True, null=True)),
                ('tzais_72', models.TimeField(blank=True, null=True)),
                ('sof_zman_krias_shema_gra', models.TimeField(blank=True, null=True)),
                ('sof_zman_krias_shema_mga', models.TimeField(blank=True, null=True)),
                ('sof_zman_tfila_gra', models.TimeField(blank=True, null=True)),
                ('sof_zman_tfila_mga', models.TimeField(blank=True, null=True)),
                ('candle_lighting', models.TimeField(blank=True, null=True)),
                ('parsha', models.CharField(blank=True, max_length=100)),
                ('daf_yomi_bavli', models.CharField(blank=True, max_length=100)),
                ('mishna_yomis', models.CharField(blank=True, max_length=100)),
                ('tehillim_monthly', models.CharField(blank=True, max_length=100)),
                ('daf_yomi_yerushalmi', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_zmanim', to='zmanim_app.shul')),
            ],
            options={
                'verbose_name_plural': 'Daily Zmanim',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['shul', 'date'], name='zmanim_app__shul_id_c60c8f_idx')],
                'unique_together': {('shul', 'date')},
            },
        ),
    ]
