# Generated by Django 5.0.8 on 2025-10-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0008_remove_shul_alos_remove_shul_candle_lighting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyzmanim',
            name='alos_16_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='alos_18',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='alos_19_8',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='daf_hashavua_bavli',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='day_of_chanukah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='day_of_omer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='elevation_adjusted_sunrise',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='elevation_adjusted_sunset',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='is_assur_bemelacha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='is_chanukah',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='is_chol_hamoed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='is_erev_rosh_chodesh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='is_erev_yom_tov',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='is_rosh_chodesh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='is_taanis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='is_yom_tov',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='jewish_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='jewish_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='jewish_month_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='jewish_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='kiddush_levana_earliest_3_days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='kiddush_levana_earliest_7_days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='kiddush_levana_latest_15_days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='molad_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='pirkei_avos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='sea_level_sunrise',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='sea_level_sunset',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='shaah_zmanis_gra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='shaah_zmanis_mga',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='significant_day',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='sun_transit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='temporal_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='tzais_5_95',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='tzais_6_45',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='tzais_7_083',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyzmanim',
            name='tzais_8_5',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
