# Generated by Django 5.0.8 on 2025-10-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0009_dailyzmanim_alos_16_1_dailyzmanim_alos_18_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShulDisplayLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_layout', to='zmanim_app.shul')),
            ],
            options={
                'verbose_name': 'Shul Display Layout',
                'verbose_name_plural': 'Shul Display Layouts',
            },
        ),
    ]
