# Generated by Django 5.0.8 on 2025-10-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0010_shuldisplaylayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyzmanim',
            name='amud_yomi_bavli_dirshu',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
