# Generated by Django 5.0.8 on 2025-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0011_dailyzmanim_amud_yomi_bavli_dirshu'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='center_logo',
            field=models.ImageField(blank=True, null=True, upload_to='shul_logos/'),
        ),
        migrations.AddField(
            model_name='shul',
            name='center_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
