# Generated by Django 5.0.8 on 2025-10-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0012_shul_center_logo_shul_center_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='center_text_size',
            field=models.IntegerField(default=48, help_text='Font size in pixels (24-96)'),
        ),
    ]
