# Generated by Django 5.0.8 on 2025-10-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0013_shul_center_text_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='center_text_color',
            field=models.CharField(default='#ffc764', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='center_text_font',
            field=models.CharField(default='Arial', help_text='Font family name', max_length=100),
        ),
        migrations.AddField(
            model_name='shul',
            name='center_vertical_position',
            field=models.IntegerField(default=50, help_text='Vertical position percentage (0=top, 50=center, 100=bottom)'),
        ),
    ]
