# Generated by Django 5.0.8 on 2025-10-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0014_shul_center_text_color_shul_center_text_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='center_logo_size',
            field=models.IntegerField(default=400, help_text='Logo max height in pixels (100-600)'),
        ),
    ]
