# Generated by Django 5.0.8 on 2025-10-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0015_shul_center_logo_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtime',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='List of days (0=Sunday, 6=Saturday)'),
        ),
        migrations.AddField(
            model_name='customtime',
            name='description',
            field=models.TextField(blank=True, help_text='Optional notes/description for this custom time'),
        ),
    ]
