# Generated by Django 5.0.8 on 2025-10-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0016_add_description_and_multiple_days_to_custom_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(help_text='Unique identifier (lowercase, no spaces)', max_length=100)),
                ('display_name', models.CharField(help_text='Label that appears on display', max_length=100)),
                ('text_type', models.CharField(choices=[('text', 'Text'), ('divider', 'Divider')], default='text', max_length=10)),
                ('text_content', models.TextField(blank=True, help_text='The text content to display (not needed for dividers)')),
                ('font_size', models.IntegerField(blank=True, help_text='Font size in pixels (leave empty to inherit from box)', null=True)),
                ('font_color', models.CharField(blank=True, help_text='Hex color code (e.g., #ffffff)', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Optional notes/description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_texts', to='zmanim_app.shul')),
            ],
            options={
                'verbose_name': 'Custom Text',
                'verbose_name_plural': 'Custom Texts',
                'ordering': ['display_name'],
                'unique_together': {('shul', 'internal_name')},
            },
        ),
    ]
