# Generated by Django 5.0.8 on 2025-10-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0017_customtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='box1_text_color',
            field=models.CharField(blank=True, default='#ffc764', help_text='Color for Box 1 text', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='box1_text_font',
            field=models.CharField(blank=True, default='Arial', help_text='Font for Box 1 text', max_length=100),
        ),
        migrations.AddField(
            model_name='shul',
            name='box1_text_size',
            field=models.IntegerField(blank=True, default=22, help_text='Font size for Box 1 text in pixels'),
        ),
        migrations.AddField(
            model_name='shul',
            name='box1_title_color',
            field=models.CharField(blank=True, default='#ffc764', help_text='Color for Box 1 title', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='box1_title_font',
            field=models.CharField(blank=True, default='Arial', help_text='Font for Box 1 title', max_length=100),
        ),
        migrations.AddField(
            model_name='shul',
            name='box2_text_color',
            field=models.CharField(blank=True, default='#ffc764', help_text='Color for Box 2 text', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='box2_text_font',
            field=models.CharField(blank=True, default='Arial', help_text='Font for Box 2 text', max_length=100),
        ),
        migrations.AddField(
            model_name='shul',
            name='box2_text_size',
            field=models.IntegerField(blank=True, default=22, help_text='Font size for Box 2 text in pixels'),
        ),
        migrations.AddField(
            model_name='shul',
            name='box2_title_color',
            field=models.CharField(blank=True, default='#ffc764', help_text='Color for Box 2 title', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='box2_title_font',
            field=models.CharField(blank=True, default='Arial', help_text='Font for Box 2 title', max_length=100),
        ),
        migrations.AddField(
            model_name='shul',
            name='box3_text_color',
            field=models.CharField(blank=True, default='#ffc764', help_text='Color for Box 3 text', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='box3_text_font',
            field=models.CharField(blank=True, default='Arial', help_text='Font for Box 3 text', max_length=100),
        ),
        migrations.AddField(
            model_name='shul',
            name='box3_text_size',
            field=models.IntegerField(blank=True, default=18, help_text='Font size for Box 3 text in pixels'),
        ),
        migrations.AddField(
            model_name='shul',
            name='box4_text_color',
            field=models.CharField(blank=True, default='#ffc764', help_text='Color for Box 4 text', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='box4_text_font',
            field=models.CharField(blank=True, default='Arial', help_text='Font for Box 4 text', max_length=100),
        ),
        migrations.AddField(
            model_name='shul',
            name='box4_text_size',
            field=models.IntegerField(blank=True, default=18, help_text='Font size for Box 4 text in pixels'),
        ),
    ]
