# Generated by Django 5.0.8 on 2025-10-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0018_add_box_styling_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='boxes_outline_color',
            field=models.CharField(blank=True, default='#d4af37', help_text='Outline color for all 6 boxes', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='header_bg_color',
            field=models.CharField(blank=True, default='#162A45', help_text='Background color for header', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='header_text_color',
            field=models.CharField(blank=True, default='#ffc764', help_text='Text color for header', max_length=7),
        ),
    ]
