# Generated by Django 5.0.8 on 2025-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0019_shul_boxes_outline_color_shul_header_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='background_color',
            field=models.CharField(blank=True, default='#000000', help_text='Background color for solid color option', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Custom background image', null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='shul',
            name='background_type',
            field=models.CharField(choices=[('default', 'Default Background'), ('color', 'Solid Color'), ('image', 'Custom Image')], default='default', help_text='Type of background', max_length=10),
        ),
    ]
