# Generated by Django 5.0.8 on 2025-10-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0020_shul_background_color_shul_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='boxes_background_color',
            field=models.CharField(blank=True, default='', help_text='Background color for all 6 boxes (leave empty for transparent)', max_length=7),
        ),
    ]
