# Generated by Django 5.0.8 on 2025-10-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0021_shul_boxes_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='ilui_nishmat',
            field=models.JSONField(blank=True, default=list, help_text='List of names for Ilui Nishmat (In Memory Of)'),
        ),
        migrations.AddField(
            model_name='shul',
            name='refuah_shleima',
            field=models.JSONField(blank=True, default=list, help_text='List of names for Refuah Shleima (Complete Healing)'),
        ),
    ]
