# Generated by Django 5.0.8 on 2025-10-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0022_shul_ilui_nishmat_shul_refuah_shleima'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMemorialBoxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilui_nishmat', models.JSONField(blank=True, default=list, help_text='List of names for Ilui Nishmat (In Memory Of)')),
                ('refuah_shleima', models.JSONField(blank=True, default=list, help_text='List of names for Refuah Shleima (Complete Healing)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Memorial Boxes',
                'verbose_name_plural': 'Global Memorial Boxes',
            },
        ),
    ]
