# Generated by Django 5.0.8 on 2025-10-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0023_globalmemorialboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='last_display_access',
            field=models.DateTimeField(blank=True, help_text='Last time the display page was accessed', null=True),
        ),
    ]
