# Generated by Django 5.0.8 on 2025-10-13 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0024_shul_last_display_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shul',
            name='language',
            field=models.CharField(choices=[('he', 'Hebrew'), ('en', 'English'), ('a', 'Ashkenazic'), ('s', 'Sephardic'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('ru', 'Russian'), ('pl', 'Polish'), ('fi', 'Finnish'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('ashkenazi_romanian', 'Romanian (Ashk.)'), ('uk', 'Ukrainian'), ('sh', 'Sephardic + Hebrew'), ('ah', 'Ashkenazic + Hebrew')], default='s', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(help_text='Name of the synagogue/organization', max_length=200)),
                ('contact_name', models.CharField(help_text='Full name of contact person', max_length=200)),
                ('email', models.EmailField(help_text='Email address for account', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Physical address of organization')),
                ('location_description', models.CharField(blank=True, help_text='City, State/Country', max_length=200)),
                ('purpose', models.TextField(help_text='Why they need this service')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_used', models.BooleanField(default=False)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (optional)')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Registration',
                'verbose_name_plural': 'Pending Registrations',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
