# Generated by Django 5.0.8 on 2025-10-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0025_alter_shul_language_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='rabbi',
            field=models.CharField(blank=True, help_text='Name of the rabbi (optional)', max_length=200),
        ),
    ]
