# Generated by Django 5.0.8 on 2025-10-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0026_pendingregistration_rabbi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='address',
            field=models.TextField(help_text='Physical address of organization'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='location_description',
            field=models.CharField(help_text='City, State/Country', max_length=200),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='organization_name',
            field=models.CharField(help_text='Name of the shul/organization', max_length=200),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='phone',
            field=models.CharField(help_text='Phone number', max_length=20),
        ),
    ]
