# Generated by Django 5.0.8 on 2025-10-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0027_alter_pendingregistration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='city',
            field=models.CharField(default='', help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='country',
            field=models.CharField(default='United States', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='state',
            field=models.CharField(default='', help_text='State/Province/Region', max_length=100),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='street_address',
            field=models.CharField(default='', help_text='Street address', max_length=300),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='zip_code',
            field=models.CharField(default='', help_text='Zip/Postal Code', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='address',
            field=models.TextField(blank=True, help_text='Full formatted address (auto-populated)'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='location_description',
            field=models.CharField(blank=True, help_text='City, State/Country (auto-populated)', max_length=200),
        ),
    ]
