# Generated by Django 5.0.8 on 2025-10-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0028_pendingregistration_city_pendingregistration_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shul',
            name='language',
            field=models.CharField(choices=[('he', 'Hebrew'), ('en', 'English'), ('a', 'Ashkenazic'), ('s', 'Sephardic'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('ru', 'Russian'), ('pl', 'Polish'), ('fi', 'Finnish'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('ashkenazi_romanian', 'Romanian (Ashk.)'), ('uk', 'Ukrainian'), ('sh', 'Sephardic + Hebrew'), ('ah', 'Ashkenazic + Hebrew')], default='he', max_length=20),
        ),
    ]
