# Generated by Django 5.0.8 on 2025-10-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0029_alter_shul_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shul',
            name='language',
            field=models.CharField(choices=[('he', 'Hebrew'), ('en', 'English'), ('s', 'Sephardic'), ('a', 'Ashkenazic')], default='he', max_length=20),
        ),
    ]
