# Generated by Django 5.0.8 on 2025-10-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0030_alter_shul_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtime',
            name='calculation_mode',
            field=models.CharField(choices=[('daily', "Daily (each day's own calculation)"), ('weekly_target', "Weekly Target Day (show specific weekday's time)"), ('specific_date', "Specific Calendar Date (show one date's time)")], default='daily', help_text='How to calculate the time: daily, weekly target day, or specific date', max_length=20),
        ),
        migrations.AddField(
            model_name='customtime',
            name='specific_date',
            field=models.DateField(blank=True, help_text='For specific_date mode: the exact date to calculate from', null=True),
        ),
        migrations.AddField(
            model_name='customtime',
            name='target_weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], help_text='For weekly_target mode: which weekday to calculate from (0=Sunday, 6=Saturday)', null=True),
        ),
        migrations.AlterField(
            model_name='customtime',
            name='daily',
            field=models.BooleanField(default=False, help_text='Display on all days of the week'),
        ),
        migrations.AlterField(
            model_name='customtime',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Display on specific days (0=Sunday, 6=Saturday)'),
        ),
    ]
