# Generated by Django 5.0.8 on 2025-10-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0031_alter_customtime_calculation_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='line_thickness',
            field=models.IntegerField(blank=True, help_text='Line space thickness in pixels (1-200, default 40)', null=True),
        ),
        migrations.AlterField(
            model_name='customtext',
            name='text_type',
            field=models.CharField(choices=[('text', 'Text'), ('divider', 'Divider'), ('line_space', 'Line Space')], default='text', max_length=20),
        ),
    ]
