# Generated by Django 5.0.8 on 2025-10-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0032_customtext_line_thickness_alter_customtext_text_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Text alignment (left, center, right)', max_length=10),
        ),
    ]
