# Generated by Django 5.0.8 on 2025-10-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0033_customtext_text_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='box5_text_color',
            field=models.CharField(blank=True, default='#ffc764', help_text='Color for Box 5 text', max_length=7),
        ),
        migrations.AddField(
            model_name='shul',
            name='box5_text_font',
            field=models.CharField(blank=True, default='Arial', help_text='Font for Box 5 text', max_length=100),
        ),
        migrations.AddField(
            model_name='shul',
            name='box5_text_size',
            field=models.IntegerField(blank=True, default=24, help_text='Font size for Box 5 text in pixels'),
        ),
    ]
