# Generated by Django 5.0.8 on 2025-10-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmanim_app', '0034_shul_box5_text_color_shul_box5_text_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shul',
            name='show_box5',
            field=models.BooleanField(default=False, help_text='Show or hide Box 5 on the display'),
        ),
    ]
